/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.ArbolAVL;
import Modelos.Archivo;
import Modelos.MatrizAdyacente;
import Modelos.NodoMatriz;
import Modelos.Usuario;
import Principal.Main;
import static Vistas.VentanaArchivos.replaceLast;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import manejador.ListEntry;
import manejador.ListEntryCellRenderer;

/**
 *
 * @author User
 */
public final class VentanaArchivos extends javax.swing.JFrame {

    int yPadre=1;
 
    NodoMatriz nodoPadre;
    NodoMatriz interseccion;
    /**
     * Creates new form ManejarArchivos
     */
    public VentanaArchivos() {
        initComponents();
        nodoPadre = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, yPadre);
        LlenarCarpetas();
        LlenarArchivos();
        interseccion = null;
    }
    
    
    public void LlenarCarpetas(){
        NodoMatriz temp = nodoPadre.getDerecha();
        DefaultListModel dlm = new DefaultListModel();
        while(true){
            if(temp!=null){
                 Icon x = new ImageIcon(getClass().getResource("/multimedia/carpeta.png")); 
                 dlm.addElement(new ListEntry(temp.getArbolAVL().getRuta(), scaleImage((ImageIcon) x,50,50), new JButton("x")));
                 temp = temp.getDerecha();
            }else{
                break;
            }
        }
        jListCarpetas.setModel(dlm);
        jListCarpetas.setCellRenderer(new ListEntryCellRenderer());
        jListCarpetas.updateUI();
        this.jTextContenido.setText("");
        this.jTextFileName.setText("");
        this.jFecha.setText("");
    }

    public void LlenarArchivos(){
        NodoMatriz temp;
        if(this.interseccion==null){
            temp = this.nodoPadre;
        }else{
            temp = this.interseccion;
        }

        DefaultListModel dlm = new DefaultListModel();
        temp.getArbolAVL().inno();
        for(Archivo a: temp.getArbolAVL().getListaArchivos() ){
             Icon x = new ImageIcon(getClass().getResource("/multimedia/archivo.png")); 
             dlm.addElement(new ListEntry(a.getNombreArchivo(), scaleImage((ImageIcon) x,50,50), new JButton("x")));
        }
        jListArchivos.setModel(dlm);
        jListArchivos.setCellRenderer(new ListEntryCellRenderer());
        jListArchivos.updateUI();
        this.jTextContenido.setText("");
        this.jTextFileName.setText("");
        this.jFecha.setText("");
    }
    
    
    public static  ImageIcon scaleImage(ImageIcon icon, int w, int h){
        int nw = icon.getIconWidth();
        int nh = icon.getIconHeight();

        if(icon.getIconWidth() > w)
        {
          nw = w;
          nh = (nw * icon.getIconHeight()) / icon.getIconWidth();
        }

        if(nh > h)
        {
          nh = h;
          nw = (icon.getIconWidth() * nh) / icon.getIconHeight();
        }

        return new ImageIcon(icon.getImage().getScaledInstance(nw, nh, Image.SCALE_AREA_AVERAGING));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCrearCarpeta = new javax.swing.JButton();
        jbusacador = new javax.swing.JTextField();
        jGraficar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCarpetas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jAbrirCarpeta = new javax.swing.JButton();
        jCrearArchivo = new javax.swing.JButton();
        jGraficar1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        EliminarArchivo = new javax.swing.JButton();
        jEditar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextContenido = new javax.swing.JTextArea();
        jTextFileName = new javax.swing.JTextField();
        jFecha = new javax.swing.JLabel();
        jGrafo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonCompartir = new javax.swing.JButton();
        jButtonEliminarArchivos = new javax.swing.JButton();
        jButtonEliminarCarpetas = new javax.swing.JButton();
        jButtonEditarCarpeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jCrearCarpeta.setText("Crear");
        jCrearCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearCarpetaActionPerformed(evt);
            }
        });

        jbusacador.setText("./");

        jGraficar.setText("Ver Matriz");
        jGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGraficarActionPerformed(evt);
            }
        });

        jBuscar.setText("buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Carpetas");

        jLabel2.setText("Archivos");

        jListCarpetas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCarpetas);
        jListCarpetas.getAccessibleContext().setAccessibleName("");
        jListCarpetas.getAccessibleContext().setAccessibleDescription("");

        jListArchivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListArchivosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListArchivos);

        jAbrirCarpeta.setText("Abrir");
        jAbrirCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirCarpetaActionPerformed(evt);
            }
        });

        jCrearArchivo.setText("Crear");
        jCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearArchivoActionPerformed(evt);
            }
        });

        jGraficar1.setText("Ver Arbol");
        jGraficar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGraficar1ActionPerformed(evt);
            }
        });

        EliminarArchivo.setText("Eliminar");
        EliminarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarArchivoActionPerformed(evt);
            }
        });

        jEditar.setText("Editar");
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });

        jTextContenido.setColumns(20);
        jTextContenido.setRows(5);
        jScrollPane3.setViewportView(jTextContenido);

        jFecha.setText("Fecha:");

        jGrafo.setText("ver Grafo");
        jGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrafoActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar Sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonCompartir.setText("Compartir");
        jButtonCompartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompartirActionPerformed(evt);
            }
        });

        jButtonEliminarArchivos.setText("Carga Masiva");
        jButtonEliminarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarArchivosActionPerformed(evt);
            }
        });

        jButtonEliminarCarpetas.setText("Eliminar");
        jButtonEliminarCarpetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCarpetasActionPerformed(evt);
            }
        });

        jButtonEditarCarpeta.setText("Editar");
        jButtonEditarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCarpetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbusacador, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCrearArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGraficar1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jButtonCompartir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEliminarArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EliminarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFileName)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(jFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCrearCarpeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGraficar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jAbrirCarpeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGrafo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEliminarCarpetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarCarpeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbusacador, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBuscar)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jGraficar)
                        .addGap(11, 11, 11)
                        .addComponent(jGrafo)
                        .addGap(13, 13, 13)
                        .addComponent(jCrearCarpeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAbrirCarpeta)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarCarpetas)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarCarpeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTextFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jGraficar1))
                        .addGap(2, 2, 2)
                        .addComponent(jButtonEliminarArchivos)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCrearArchivo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCompartir)
                                .addGap(18, 18, 18)
                                .addComponent(jEditar)
                                .addGap(18, 18, 18)
                                .addComponent(EliminarArchivo))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCrearCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearCarpetaActionPerformed
        try{
            String nombreCarpeta = "Nuvea" + LocalDateTime.now().toString();
        nombreCarpeta = JOptionPane.showInputDialog(null, "Nombre de Carpeta");
        if(nombreCarpeta.contains("/")){
            JOptionPane.showMessageDialog(null, "No se permite llamar asi la carpeta");
            return;
        }
        int x=0;
        while(true){
            if(Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, yPadre+x)==null){
                Sesion.Usuarioglobal.getMatrizAdyacente().insertar_elementos(yPadre+x, 0, new ArbolAVL(nodoPadre.getArbolAVL().getRuta()+nombreCarpeta+"/",nombreCarpeta,nombreCarpeta));
                Sesion.Usuarioglobal.getMatrizAdyacente().insertar_elementos(0, yPadre+x, new ArbolAVL(nodoPadre.getArbolAVL().getRuta()+nombreCarpeta+"/",nombreCarpeta,nombreCarpeta));
                Sesion.Usuarioglobal.getMatrizAdyacente().insertarEnLaInterseccion(nodoPadre.getArbolAVL().getRuta(), nodoPadre.getArbolAVL().getRuta()+nombreCarpeta+"/", nodoPadre.getArbolAVL().getNombreAuxiliar()+"/"+nombreCarpeta, nombreCarpeta);
                break;
            }else{
                x++;
            }

        }
        LlenarCarpetas();
        }catch(NullPointerException n){
            
        }
    }//GEN-LAST:event_jCrearCarpetaActionPerformed

    
    private void jGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGraficarActionPerformed
        Sesion.Usuarioglobal.getMatrizAdyacente().graficar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jGraficarActionPerformed

    private void jAbrirCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirCarpetaActionPerformed
        try{
            NodoMatriz temp = nodoPadre.getDerecha();
         int index = jListCarpetas.getSelectedIndex();
         for(int i=0; i<index;i++){
             temp = temp.getDerecha();
         }
         System.out.println(temp.getArbolAVL().getRuta());
         System.out.println("--------------------------------------------");
         System.out.println(temp.getY());
         NodoMatriz padreTemp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, temp.getY());
         System.out.println("********************************************");
         Sesion.Usuarioglobal.getMatrizAdyacente().recorrer();
                  
         String relacion = temp.getArbolAVL().getRuta();
         this.interseccion = temp;
         this.jbusacador.setText(interseccion.getArbolAVL().getRuta());
       //  System.out.println(relacion[1]);
         
         while(true){
             if(padreTemp.getArbolAVL().getRuta().equals(relacion)){
                 nodoPadre = padreTemp;
                 break;
             }else{
                 padreTemp = padreTemp.getAbajo();
             }
         }        
         
         this.yPadre = nodoPadre.getY();
         LlenarArchivos();
         LlenarCarpetas();
        }catch(NullPointerException w){
            
        }
        
    }//GEN-LAST:event_jAbrirCarpetaActionPerformed

    private void jCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearArchivoActionPerformed
        try{
        String nombreArchivo = "Nuevo"+LocalDateTime.now().toString()+".txt";
        nombreArchivo = JOptionPane.showInputDialog(null, "Nombre del Archivo");
        
        if(nombreArchivo==null){
            return;
        }
        
        JTextArea ta = new JTextArea(20, 20);
        ta.setText("Ingrese Contenido");
        switch (JOptionPane.showConfirmDialog(null, new JScrollPane(ta))) {
            case JOptionPane.OK_OPTION:
                System.out.println(ta.getText());
                break;        
        }
        String contenidoArchivo = ta.getText().replaceAll("\"", "");
        nombreArchivo = nombreArchivo.replaceAll("\"", "");
        if(this.interseccion==null){
            NodoMatriz temp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(nodoPadre.getX(), nodoPadre.getY());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(new Archivo(nombreArchivo,contenidoArchivo));
            
        }else{
             NodoMatriz temp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(interseccion.getX(), interseccion.getY());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(new Archivo(nombreArchivo,contenidoArchivo));
        }
        LlenarArchivos();
        }catch(NullPointerException r){
            
        }
       
    }//GEN-LAST:event_jCrearArchivoActionPerformed

    
    private void jGraficar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGraficar1ActionPerformed
        if(interseccion!=null){
            interseccion.getArbolAVL().inno();
            if(interseccion.getArbolAVL().getListaArchivos().size() > 1){
                interseccion.getArbolAVL().graficar();
            }
            else{
                JOptionPane.showMessageDialog(null, "Se neceita al menos 2 archivos para graficar");
            }
            
        }else{
            nodoPadre.getArbolAVL().inno();
            if(nodoPadre.getArbolAVL().getListaArchivos().size() > 1){
                this.nodoPadre.getArbolAVL().graficar();
            }
            else{
                JOptionPane.showMessageDialog(null, "Se neceita al menos 2 archivos para graficar");
            }  
        }
    }//GEN-LAST:event_jGraficar1ActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        interseccion = Sesion.Usuarioglobal.getMatrizAdyacente().buscarInterseccion(this.jbusacador.getText());
        if(interseccion!=null){
            NodoMatriz padreTemp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, interseccion.getY());
            
            while(true){
             if(padreTemp.getArbolAVL().getRuta().equals(interseccion.getArbolAVL().getRuta())){
                 nodoPadre = padreTemp;
                 break;
             }else{
                 padreTemp = padreTemp.getAbajo();
             }
         }        
            
        }
        else{
            nodoPadre = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, 1);
            this.yPadre = 1;
            interseccion =  null;
            this.jbusacador.setText("./");
        }
         this.yPadre = nodoPadre.getY();
        LlenarArchivos();
        LlenarCarpetas();
    }//GEN-LAST:event_jBuscarActionPerformed

    private void EliminarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarArchivoActionPerformed
        try{
            int reply = JOptionPane.showConfirmDialog(null, "desea eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            if(interseccion == null){
                NodoMatriz temp = this.nodoPadre;
                temp.getArbolAVL().inno();
                Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
                Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
            }else{
                NodoMatriz temp = this.interseccion;
                temp.getArbolAVL().inno();
                Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
                Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
            }
        this.LlenarArchivos();
        }
        }catch(ArrayIndexOutOfBoundsException r){
            
        }
        
    }//GEN-LAST:event_EliminarArchivoActionPerformed

    private void jListArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListArchivosMouseClicked
        try{
             Archivo archivo;
        if(interseccion == null){
            NodoMatriz temp = this.nodoPadre;
            temp.getArbolAVL().inno();
            archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
        }else{
            NodoMatriz temp = this.interseccion;
            temp.getArbolAVL().inno();
            archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());            
        }
        
        this.jTextContenido.setText(archivo.getContenido());
        this.jTextFileName.setText(archivo.getNombreArchivo());
        this.jFecha.setText(archivo.getFechas().toString());
            
        }catch(ArrayIndexOutOfBoundsException r){
            
        }
       
    }//GEN-LAST:event_jListArchivosMouseClicked

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
        if(interseccion == null){
            NodoMatriz temp = this.nodoPadre;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Archivo archivo2 = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
            archivo2.setContenido(this.jTextContenido.getText());
            archivo2.setNombreArchivo(this.jTextFileName.getText());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(archivo2);
            
        }else{
            NodoMatriz temp = this.interseccion;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Archivo archivo2 = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            archivo2.setContenido(this.jTextContenido.getText());
            archivo2.setNombreArchivo(this.jTextFileName.getText());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(archivo2);
        }
        this.LlenarArchivos();
    }//GEN-LAST:event_jEditarActionPerformed

    private void jGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrafoActionPerformed
           Sesion.Usuarioglobal.getMatrizAdyacente().grafo();
    }//GEN-LAST:event_jGrafoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Sesion s = new Sesion();
        this.dispose();
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCompartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompartirActionPerformed
        try{            
            if(interseccion == null){
            NodoMatriz temp = this.nodoPadre;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            String amigo = "";
            amigo =JOptionPane.showInputDialog(null, "Ingrese usuario a compartir"); 
            Main.tablaHash.Compartir(amigo, archivo);
            
        }else{
            NodoMatriz temp = this.interseccion;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            String amigo = "";
            amigo =JOptionPane.showInputDialog(null, "Ingrese usuario a compartir"); 
            Main.tablaHash.Compartir(amigo, archivo);
        }
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Seleccione un archivo correctamente");
        }
        
    }//GEN-LAST:event_jButtonCompartirActionPerformed

    private void jButtonEliminarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarArchivosActionPerformed
        BufferedReader br = null;
        try {        
            FileNameExtensionFilter filtro = new FileNameExtensionFilter(null, "csv");
            JFileChooser buscador = new JFileChooser();
            buscador.setFileFilter(filtro); 
            buscador.addChoosableFileFilter(filtro);
            buscador.showOpenDialog(buscador);    
                    
            String patch  = buscador.getSelectedFile().getAbsolutePath();
                if(patch.endsWith(".csv") | patch.endsWith(".CSV") ){
                                             
                FileReader archivo = new FileReader(patch);
                br = new BufferedReader(new InputStreamReader(new FileInputStream(patch), "UTF8"));
                String line = "";    
                int x =0;
                int columnaArchivo = 0;
                int columnaContenido = 1;
                boolean bandera1 = false;
                boolean bandera2 = false;
                String delimitador = JOptionPane.showInputDialog(null, "Signo de separcion");
                    while ((line = br.readLine().trim()) != null) {
                        String[] separar = line.split(delimitador,2);                
                        try{                           
                        
                            if(x==0){
                                if(separar[0].equals("Archivo")){
                                    columnaArchivo = 0;
                                    bandera1 = true;
                                }
                                if(separar[0].equals("Contenido")){
                                    columnaContenido = 0;
                                    bandera1 = true;
                                }
                                if(separar[1].equals("Archivo")){
                                    columnaArchivo = 1;
                                    bandera2 = true;
                                }
                                if(separar[1].equals("Contenido")){
                                    columnaContenido = 1;
                                    bandera2 = true;
                                }
                                
                                if(bandera1 && bandera2){
                                    x++;
                                }else{
                                    JOptionPane.showMessageDialog(null, "Cabeceras de archivo invalidades");
                                    break;
                                }
                                
                                continue;
                            }
                        
                            
                            String nombreArchivo = separar[columnaArchivo].replace("\"", "");
                            String contenidoArchivo = separar[columnaContenido].replace("\"", "");
                                
                                if(this.interseccion==null){
                                    NodoMatriz temp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(nodoPadre.getX(), nodoPadre.getY());
                                    Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(new Archivo(nombreArchivo,contenidoArchivo));            
                                }else{
                                    NodoMatriz temp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(interseccion.getX(), interseccion.getY());
                                    Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(new Archivo(nombreArchivo,contenidoArchivo));
                                }
                                
                            LlenarArchivos();
 
                        }catch(Exception c){
                            JOptionPane.showMessageDialog(null, "Error en la linea:"+line);
                        }
                            
                    }
                        
                }                       
            } catch (NullPointerException e) {        
            } catch (FileNotFoundException e) {
            } catch (IOException e) {
            } finally {
                try {
                    if (null != br)
                        br.close();
                } catch (Exception e2) {
                    e2.printStackTrace();
            }
        }   
    }//GEN-LAST:event_jButtonEliminarArchivosActionPerformed

    private void jButtonEliminarCarpetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCarpetasActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "desea eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {       
        try{
            NodoMatriz temp = nodoPadre.getDerecha();
         int index = jListCarpetas.getSelectedIndex();
         for(int i=0; i<index;i++){
             temp = temp.getDerecha();
         }
         System.out.println(temp.getArbolAVL().getRuta());
         System.out.println("--------------------------------------------");
         System.out.println(temp.getY());
   
         System.out.println("********************************************");
         Sesion.Usuarioglobal.getMatrizAdyacente().recorrer();
                  
         String relacion = temp.getArbolAVL().getRuta();
         
         
         
         Sesion.Usuarioglobal.getMatrizAdyacente().eliminar(relacion);
         
         interseccion = Sesion.Usuarioglobal.getMatrizAdyacente().buscarInterseccion(this.jbusacador.getText());
         if(interseccion!=null){
            NodoMatriz padreTemp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, interseccion.getY());
            
            while(true){
             if(padreTemp.getArbolAVL().getRuta().equals(interseccion.getArbolAVL().getRuta())){
                 nodoPadre = padreTemp;
                 break;
             }else{
                 padreTemp = padreTemp.getAbajo();
             }
         }        
            
        }
        else{
            nodoPadre = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, 1);
            this.yPadre = 1;
            interseccion =  null;
            this.jbusacador.setText("./");
        }
        this.yPadre = nodoPadre.getY();
        LlenarArchivos();
        LlenarCarpetas(); 
        
        }catch(NullPointerException w){
            
        }
        }
    }//GEN-LAST:event_jButtonEliminarCarpetasActionPerformed

    private void jButtonEditarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCarpetaActionPerformed
 
       try{
            NodoMatriz temp = nodoPadre.getDerecha();
         int index = jListCarpetas.getSelectedIndex();
         for(int i=0; i<index;i++){
             temp = temp.getDerecha();
         }
         System.out.println(temp.getArbolAVL().getRuta());
         System.out.println("--------------------------------------------");
         System.out.println(temp.getY());
   
         System.out.println("********************************************");
         Sesion.Usuarioglobal.getMatrizAdyacente().recorrer();
                  
         String nombreNuevoCarpeta = JOptionPane.showInputDialog(null, "Nuevo nombre");
         String relacion = temp.getArbolAVL().getRuta();
         
         
         String rutaVieja = temp.getArbolAVL().getRuta();
         String rutaNueva = replaceLast(rutaVieja,temp.getArbolAVL().getNombreCarpeta(),nombreNuevoCarpeta);
         String auxViejo =  temp.getArbolAVL().getNombreAuxiliar();
         String auxNuevo =  replaceLast(auxViejo,temp.getArbolAVL().getNombreCarpeta(),nombreNuevoCarpeta);  
         
         
         Sesion.Usuarioglobal.getMatrizAdyacente().editar(rutaVieja, temp.getArbolAVL().getNombreCarpeta(), auxViejo, rutaNueva, nombreNuevoCarpeta, auxNuevo);
         
         interseccion = Sesion.Usuarioglobal.getMatrizAdyacente().buscarInterseccion(this.jbusacador.getText());
         if(interseccion!=null){
            NodoMatriz padreTemp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, interseccion.getY());
            
            while(true){
             if(padreTemp.getArbolAVL().getRuta().equals(interseccion.getArbolAVL().getRuta())){
                 nodoPadre = padreTemp;
                 break;
             }else{
                 padreTemp = padreTemp.getAbajo();
             }
         }        
            
        }
        else{
            nodoPadre = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, 1);
            this.yPadre = 1;
            interseccion =  null;
            this.jbusacador.setText("./");
        }
        this.yPadre = nodoPadre.getY();
        LlenarArchivos();
        LlenarCarpetas(); 
        
        }catch(NullPointerException w){
            
        }
        
    }//GEN-LAST:event_jButtonEditarCarpetaActionPerformed

    
    public static String replaceLast(String string, String toReplace, String replacement) {
    int pos = string.lastIndexOf(toReplace);
    if (pos > -1) {
        return string.substring(0, pos)
             + replacement
             + string.substring(pos + toReplace.length(), string.length());
    } else {
        return string;
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarArchivo;
    private javax.swing.JButton jAbrirCarpeta;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCompartir;
    private javax.swing.JButton jButtonEditarCarpeta;
    private javax.swing.JButton jButtonEliminarArchivos;
    private javax.swing.JButton jButtonEliminarCarpetas;
    private javax.swing.JButton jCrearArchivo;
    private javax.swing.JButton jCrearCarpeta;
    private javax.swing.JButton jEditar;
    private javax.swing.JLabel jFecha;
    private javax.swing.JButton jGraficar;
    private javax.swing.JButton jGraficar1;
    private javax.swing.JButton jGrafo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListArchivos;
    private static javax.swing.JList<String> jListCarpetas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextContenido;
    private javax.swing.JTextField jTextFileName;
    private javax.swing.JTextField jbusacador;
    // End of variables declaration//GEN-END:variables
}
