/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.ArbolAVL;
import Modelos.Archivo;
import Modelos.MatrizAdyacente;
import Modelos.NodoMatriz;
import Modelos.Usuario;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import manejador.ListEntry;
import manejador.ListEntryCellRenderer;

/**
 *
 * @author User
 */
public final class VentanaArchivos extends javax.swing.JFrame {

    int yPadre=1;
 
    NodoMatriz nodoPadre;
    NodoMatriz interseccion;
    /**
     * Creates new form ManejarArchivos
     */
    public VentanaArchivos() {
        initComponents();
        nodoPadre = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, yPadre);
        LlenarCarpetas();
        interseccion = null;
    }
    
    
    public void LlenarCarpetas(){
        NodoMatriz temp = nodoPadre.getDerecha();
        DefaultListModel dlm = new DefaultListModel();
        while(true){
            if(temp!=null){
                 Icon x = new ImageIcon(getClass().getResource("/multimedia/carpeta.png")); 
                 dlm.addElement(new ListEntry(temp.getArbolAVL().getRuta(), scaleImage((ImageIcon) x,50,50), new JButton("x")));
                 temp = temp.getDerecha();
            }else{
                break;
            }
        }
        jListCarpetas.setModel(dlm);
        jListCarpetas.setCellRenderer(new ListEntryCellRenderer());
        jListCarpetas.updateUI();
        this.jTextContenido.setText("");
        this.jTextFileName.setText("");
        this.jFecha.setText("");
    }

    public void LlenarArchivos(){
        NodoMatriz temp;
        if(this.interseccion==null){
            temp = this.nodoPadre;
        }else{
            temp = this.interseccion;
        }

        DefaultListModel dlm = new DefaultListModel();
        temp.getArbolAVL().inno();
        for(Archivo a: temp.getArbolAVL().getListaArchivos() ){
             Icon x = new ImageIcon(getClass().getResource("/multimedia/archivo.png")); 
             dlm.addElement(new ListEntry(a.getNombreArchivo(), scaleImage((ImageIcon) x,50,50), new JButton("x")));
        }
        jListArchivos.setModel(dlm);
        jListArchivos.setCellRenderer(new ListEntryCellRenderer());
        jListArchivos.updateUI();
        this.jTextContenido.setText("");
        this.jTextFileName.setText("");
        this.jFecha.setText("");
    }
    
    
    public static  ImageIcon scaleImage(ImageIcon icon, int w, int h){
        int nw = icon.getIconWidth();
        int nh = icon.getIconHeight();

        if(icon.getIconWidth() > w)
        {
          nw = w;
          nh = (nw * icon.getIconHeight()) / icon.getIconWidth();
        }

        if(nh > h)
        {
          nh = h;
          nw = (icon.getIconWidth() * nh) / icon.getIconHeight();
        }

        return new ImageIcon(icon.getImage().getScaledInstance(nw, nh, Image.SCALE_AREA_AVERAGING));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCrear = new javax.swing.JButton();
        jbusacador = new javax.swing.JTextField();
        jGraficar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCarpetas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jAbrirCarpeta = new javax.swing.JButton();
        jCrearArchivo = new javax.swing.JButton();
        jGraficar1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        EliminarArchivo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextContenido = new javax.swing.JTextArea();
        jTextFileName = new javax.swing.JTextField();
        jFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jCrear.setText("Crear");
        jCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearActionPerformed(evt);
            }
        });

        jbusacador.setText("./");

        jGraficar.setText("Graficar");
        jGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGraficarActionPerformed(evt);
            }
        });

        jBuscar.setText("buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Carpetas");

        jLabel2.setText("Archivos");

        jListCarpetas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCarpetas);
        jListCarpetas.getAccessibleContext().setAccessibleName("");
        jListCarpetas.getAccessibleContext().setAccessibleDescription("");

        jListArchivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListArchivosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListArchivos);

        jAbrirCarpeta.setText("Abrir");
        jAbrirCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirCarpetaActionPerformed(evt);
            }
        });

        jCrearArchivo.setText("Crear");
        jCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearArchivoActionPerformed(evt);
            }
        });

        jGraficar1.setText("Graficar");
        jGraficar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGraficar1ActionPerformed(evt);
            }
        });

        EliminarArchivo.setText("Eliminar");
        EliminarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarArchivoActionPerformed(evt);
            }
        });

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextContenido.setColumns(20);
        jTextContenido.setRows(5);
        jScrollPane3.setViewportView(jTextContenido);

        jFecha.setText("Fecha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCrearArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EliminarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jGraficar1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFileName)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(jFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbusacador, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jGraficar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jAbrirCarpeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbusacador, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jGraficar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAbrirCarpeta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGraficar1)
                            .addComponent(jTextFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCrearArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EliminarArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearActionPerformed
        String nombreCarpeta = JOptionPane.showInputDialog(null, "Nombre de Carpeta");
        int x=0;
        while(true){
            if(Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, yPadre+x)==null){
                Sesion.Usuarioglobal.getMatrizAdyacente().insertar_elementos(yPadre+x, 0, new ArbolAVL(nodoPadre.getArbolAVL().getRuta()+nombreCarpeta+"/"));
                Sesion.Usuarioglobal.getMatrizAdyacente().insertar_elementos(0, yPadre+x, new ArbolAVL(nodoPadre.getArbolAVL().getRuta()+nombreCarpeta+"/"));
                Sesion.Usuarioglobal.getMatrizAdyacente().insertarEnLaInterseccion(nodoPadre.getArbolAVL().getRuta(), nodoPadre.getArbolAVL().getRuta()+nombreCarpeta+"/");
                break;
            }else{
                x++;
            }

        }
        LlenarCarpetas();
    }//GEN-LAST:event_jCrearActionPerformed

    
    private void jGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGraficarActionPerformed
        Sesion.Usuarioglobal.getMatrizAdyacente().graficar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jGraficarActionPerformed

    private void jAbrirCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirCarpetaActionPerformed
         NodoMatriz temp = nodoPadre.getDerecha();
         int index = jListCarpetas.getSelectedIndex();
         for(int i=0; i<index;i++){
             temp = temp.getDerecha();
         }
         System.out.println(temp.getArbolAVL().getRuta());
         System.out.println("--------------------------------------------");
         System.out.println(temp.getY());
         NodoMatriz padreTemp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, temp.getY());
         System.out.println("********************************************");
         Sesion.Usuarioglobal.getMatrizAdyacente().recorrer();
                  
         String relacion = temp.getArbolAVL().getRuta();
         this.interseccion = temp;
         this.jbusacador.setText(interseccion.getArbolAVL().getRuta());
       //  System.out.println(relacion[1]);
         
         while(true){
             if(padreTemp.getArbolAVL().getRuta().equals(relacion)){
                 nodoPadre = padreTemp;
                 break;
             }else{
                 padreTemp = padreTemp.getAbajo();
             }
         }        
         
         this.yPadre = nodoPadre.getY();
         LlenarArchivos();
         LlenarCarpetas();
    }//GEN-LAST:event_jAbrirCarpetaActionPerformed

    private void jCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearArchivoActionPerformed
            
        String nombreArchivo = JOptionPane.showInputDialog(null, "Nombre del Archivo");
        JTextArea ta = new JTextArea(20, 20);
        ta.setText("Ingrese Contenido");
        switch (JOptionPane.showConfirmDialog(null, new JScrollPane(ta))) {
            case JOptionPane.OK_OPTION:
                System.out.println(ta.getText());
                break;        
        }
        String contenidoArchivo = ta.getText();
        
        if(this.interseccion==null){
            NodoMatriz temp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(nodoPadre.getX(), nodoPadre.getY());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(new Archivo(nombreArchivo,contenidoArchivo));
            
        }else{
             NodoMatriz temp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(interseccion.getX(), interseccion.getY());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(new Archivo(nombreArchivo,contenidoArchivo));
        }
        LlenarArchivos();
    }//GEN-LAST:event_jCrearArchivoActionPerformed

    
    private void jGraficar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGraficar1ActionPerformed
        if(interseccion!=null){
            interseccion.getArbolAVL().inno();
            if(interseccion.getArbolAVL().getListaArchivos().size() > 1){
                interseccion.getArbolAVL().graficar();
            }
            else{
                JOptionPane.showMessageDialog(null, "Se neceita al menos 2 archivos para graficar");
            }
            
        }else{
            nodoPadre.getArbolAVL().inno();
            if(nodoPadre.getArbolAVL().getListaArchivos().size() > 1){
                this.nodoPadre.getArbolAVL().graficar();
            }
            else{
                JOptionPane.showMessageDialog(null, "Se neceita al menos 2 archivos para graficar");
            }  
        }
    }//GEN-LAST:event_jGraficar1ActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        interseccion = Sesion.Usuarioglobal.getMatrizAdyacente().buscarInterseccion(this.jbusacador.getText());
        if(interseccion!=null){
            NodoMatriz padreTemp = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, interseccion.getY());
            
            while(true){
             if(padreTemp.getArbolAVL().getRuta().equals(interseccion.getArbolAVL().getRuta())){
                 nodoPadre = padreTemp;
                 break;
             }else{
                 padreTemp = padreTemp.getAbajo();
             }
         }        
            
        }
        else{
            nodoPadre = Sesion.Usuarioglobal.getMatrizAdyacente().buscar(0, 1);
            this.yPadre = 1;
            interseccion =  null;
            this.jbusacador.setText("./");
        }
         this.yPadre = nodoPadre.getY();
        LlenarArchivos();
        LlenarCarpetas();
    }//GEN-LAST:event_jBuscarActionPerformed

    private void EliminarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarArchivoActionPerformed
        if(interseccion == null){
            NodoMatriz temp = this.nodoPadre;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
        }else{
            NodoMatriz temp = this.interseccion;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
        }
        this.LlenarArchivos();
    }//GEN-LAST:event_EliminarArchivoActionPerformed

    private void jListArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListArchivosMouseClicked
        try{
             Archivo archivo;
        if(interseccion == null){
            NodoMatriz temp = this.nodoPadre;
            temp.getArbolAVL().inno();
            archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
        }else{
            NodoMatriz temp = this.interseccion;
            temp.getArbolAVL().inno();
            archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());            
        }
        
        this.jTextContenido.setText(archivo.getContenido());
        this.jTextFileName.setText(archivo.getNombreArchivo());
        this.jFecha.setText(archivo.getFechas().toString());
            
        }catch(ArrayIndexOutOfBoundsException r){
            
        }
       
    }//GEN-LAST:event_jListArchivosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(interseccion == null){
            NodoMatriz temp = this.nodoPadre;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Archivo archivo2 = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
            archivo2.setContenido(this.jTextContenido.getText());
            archivo2.setNombreArchivo(this.jTextFileName.getText());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(archivo2);
            
        }else{
            NodoMatriz temp = this.interseccion;
            temp.getArbolAVL().inno();
            Archivo archivo = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            Archivo archivo2 = temp.getArbolAVL().getListaArchivos().get(this.jListArchivos.getSelectedIndex());
            archivo2.setContenido(this.jTextContenido.getText());
            archivo2.setNombreArchivo(this.jTextFileName.getText());
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().Eliminar(archivo);
            Sesion.Usuarioglobal.getMatrizAdyacente().buscar(temp.getX(),temp.getY()).getArbolAVL().insertar(archivo2);
        }
        this.LlenarArchivos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarArchivo;
    private javax.swing.JButton jAbrirCarpeta;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCrear;
    private javax.swing.JButton jCrearArchivo;
    private javax.swing.JLabel jFecha;
    private javax.swing.JButton jGraficar;
    private javax.swing.JButton jGraficar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListArchivos;
    private static javax.swing.JList<String> jListCarpetas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextContenido;
    private javax.swing.JTextField jTextFileName;
    private javax.swing.JTextField jbusacador;
    // End of variables declaration//GEN-END:variables
}
